# Generated by Django 4.2.5 on 2023-10-01 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "contact",
                    models.CharField(max_length=50, verbose_name="Способ связаться!"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Тема")),
                (
                    "description",
                    models.TextField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            1,
                            16,
                            42,
                            33,
                            434741,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложения или жалоба",
                "verbose_name_plural": "Предложении или жалобы",
                "ordering": ["-date_created", "name", "title"],
            },
        ),
    ]
